### DISCUSSION TITLE
Docker Setup with Cloudflare Tunnel

### DISCUSSION THREAD

**Discussion by felix-exon** [frappe/helpdesk#2130] [Q&A]
Hi there,

i have the following compose:

```yml
name: helpdesk_prod_setup
services:
  backend:
    depends_on:
      configurator:
        condition: service_completed_successfully
    image: ghcr.io/frappe/helpdesk:stable
    networks:
      default: null
    platform: linux/amd64
    pull_policy: missing
    volumes:
      - type: volume
        source: sites
        target: /home/frappe/frappe-bench/sites
        volume: {}

  configurator:
    command:
      - |
        ls -1 apps > sites/apps.txt; bench set-config -g db_host $$DB_HOST; \
        bench set-config -gp db_port $$DB_PORT; \
        bench set-config -g redis_cache "redis://$$REDIS_CACHE"; \
        bench set-config -g redis_queue "redis://$$REDIS_QUEUE"; \
        bench set-config -g redis_socketio "redis://$$REDIS_QUEUE"; \
        bench set-config -gp socketio_port $$SOCKETIO_PORT;
    depends_on:
      db:
        condition: service_healthy
      redis-cache:
        condition: service_started
      redis-queue:
        condition: service_started
    entrypoint:
      - bash
      - -c
    environment:
      DB_HOST: db
      DB_PORT: "3306"
      REDIS_CACHE: redis-cache:6379
      REDIS_QUEUE: redis-queue:6379
      SOCKETIO_PORT: "9000"
    image: ghcr.io/frappe/helpdesk:stable
    networks:
      default: null
    platform: linux/amd64
    pull_policy: missing
    volumes:
      - type: volume
        source: sites
        target: /home/frappe/frappe-bench/sites
        volume: {}

  cron:
    command:
      - daemon
      - --docker
    depends_on:
      scheduler:
        condition: service_started
    image: mcuadros/ofelia:latest
    networks:
      default: null
    volumes:
      - type: bind
        source: /var/run/docker.sock
        target: /var/run/docker.sock
        read_only: true
        bind:
          create_host_path: true

  db:
    command:
      - --character-set-server=utf8mb4
      - --collation-server=utf8mb4_unicode_ci
      - --skip-character-set-client-handshake
      - --skip-innodb-read-only-compressed
    environment:
      MYSQL_ROOT_PASSWORD: 1c8167920
    healthcheck:
      test:
        - CMD-SHELL
        - mysqladmin ping -h localhost --password=123456789
      interval: 1s
      retries: 20
    image: mariadb:10.6
    networks:
      default: null
    volumes:
      - /volume1/docker/frappe_helpdesk/mariadb/:/var/lib/mysql

  frontend:
    command:
      - nginx-entrypoint.sh
    depends_on:
      backend:
        condition: service_started
      websocket:
        condition: service_started
    environment:
      BACKEND: backend:8000
      CLIENT_MAX_BODY_SIZE: 50m
      FRAPPE_SITE_NAME_HEADER: $$host
      PROXY_READ_TIMEOUT: "120"
      SOCKETIO: websocket:9000
      UPSTREAM_REAL_IP_ADDRESS: 127.0.0.1
      UPSTREAM_REAL_IP_HEADER: X-Forwarded-For
      UPSTREAM_REAL_IP_RECURSIVE: "off"
    image: ghcr.io/frappe/helpdesk:stable
    labels:
      # Traefik-Labels,  HTTP only
      traefik.enable: "true"
      traefik.http.routers.frontend-http.rule: Host(`helpdesk.mydomain.io`)
      traefik.http.routers.frontend-http.entrypoints: web
      traefik.http.services.frontend.loadbalancer.server.port: "8080"
    networks:
      default: null
    platform: linux/amd64
    pull_policy: missing
    volumes:
      - type: volume
        source: sites
        target: /home/frappe/frappe-bench/sites
        volume: {}

  proxy:
    # Traefik nur für HTTP
    command:
      - --providers.docker=true
      - --providers.docker.exposedbydefault=false
      - --entrypoints.web.address=:80
      - --log.level=DEBUG
    image: traefik:v2.11
    networks:
      default: null
    ports:
      - mode: ingress
        target: 80
        published: "7080"  # <-- HTTP HOST PORT
        protocol: tcp
    volumes:
      - type: bind
        source: /var/run/docker.sock
        target: /var/run/docker.sock
        read_only: true
        bind:
          create_host_path: true

  queue-long:
    command:
      - bench
      - worker
      - --queue
      - long,default,short
    depends_on:
      configurator:
        condition: service_completed_successfully
    image: ghcr.io/frappe/helpdesk:stable
    networks:
      default: null
    platform: linux/amd64
    pull_policy: missing
    volumes:
      - type: volume
        source: sites
        target: /home/frappe/frappe-bench/sites
        volume: {}

  queue-short:
    command:
      - bench
      - worker
      - --queue
      - short,default
    depends_on:
      configurator:
        condition: service_completed_successfully
    image: ghcr.io/frappe/helpdesk:stable
    networks:
      default: null
    platform: linux/amd64
    pull_policy: missing
    volumes:
      - type: volume
        source: sites
        target: /home/frappe/frappe-bench/sites
        volume: {}

  redis-cache:
    image: redis:6.2-alpine
    networks:
      default: null
    volumes:
      - type: volume
        source: redis-cache-data
        target: /data
        volume: {}

  redis-queue:
    image: redis:6.2-alpine
    networks:
      default: null
    volumes:
      - type: volume
        source: redis-queue-data
        target: /data
        volume: {}

  scheduler:
    command:
      - bench
      - schedule
    depends_on:
      configurator:
        condition: service_completed_successfully
    image: ghcr.io/frappe/helpdesk:stable
    labels:
      ofelia.enabled: "true"
      ofelia.job-exec.datecron.command: bench --site all backup
      ofelia.job-exec.datecron.schedule: '@every 6h'
      ofelia.job-exec.datecron.user: frappe
    networks:
      default: null
    platform: linux/amd64
    pull_policy: missing
    volumes:
      - type: volume
        source: sites
        target: /home/frappe/frappe-bench/sites
        volume: {}

  websocket:
    command:
      - node
      - /home/frappe/frappe-bench/apps/frappe/socketio.js
    depends_on:
      configurator:
        condition: service_completed_successfully
    image: ghcr.io/frappe/helpdesk:stable
    networks:
      default: null
    platform: linux/amd64
    pull_policy: missing
    volumes:
      - type: volume
        source: sites
        target: /home/frappe/frappe-bench/sites
        volume: {}

networks:
  default:
    name: helpdesk_prod_setup_default

volumes:
  db-data:
    name: helpdesk_prod_setup_db-data
  redis-cache-data:
    name: helpdesk_prod_setup_redis-cache-data
  redis-queue-data:
    name: helpdesk_prod_setup_redis-queue-data
  sites:
    name: helpdesk_prod_setup_sites
```

When i visit my site `helpdesk.mydomain.io` I just get 404:

![image](https://github.com/user-attachments/assets/9d7d35d7-7138-4d32-998e-ee50b2bba638)

Traffic seems to reach my frontend container:

![image](https://github.com/user-attachments/assets/575711c0-269b-40d5-a784-22a311f824b1)

Any hints on what could be wrong?
