### ISSUE TITLE
Helpdesk installaion - blank page (missing js and css files)

### ISSUE THREAD

**Issue by twarogowski** [frappe/helpdesk#2243]
### Information about bug

Hello,
after fresh installation of Frappe Helpdesk, using docker-compose method, as suggested in manual, I get a blank page instead of agent portal view.

for app selector page (http://localhost:8000/apps) favicon.svg is missing
for http://localhost:8000/helpdesk, more files are missing, specifically:
http://localhost:8000/assets/helpdesk/desk/assets/index-1f186735.js
http://localhost:8000/assets/helpdesk/desk/assets/index-998a7811.css
http://localhost:8000/assets/helpdesk/desk/registerSW.js
http://localhost:8000/assets/helpdesk/desk/manifest.webmanifest

probablby this is why  get blank page :(

here is my docker-compose.yml:

```
version: "3.7"
services:
  mariadb:
    image: mariadb:10.8
    command:
      - --character-set-server=utf8mb4
      - --collation-server=utf8mb4_unicode_ci
      - --skip-character-set-client-handshake
      - --skip-innodb-read-only-compressed # Temporary fix for MariaDB 10.6
    environment:
      MYSQL_ROOT_PASSWORD: 123
    volumes:
      - mariadb-data:/var/lib/mysql

  redis:
    image: redis:alpine

  frappe:
    image: frappe/bench:latest
    command: bash /workspace/init.sh
    environment:
      - SHELL=/bin/bash
    working_dir: /home/frappe
    volumes:
      - .:/workspace
    ports:
      - 8000:8000
      - 9000:9000

volumes:
  mariadb-data:
```

and my init.sh:

```#!bin/bash

if [ -d "/home/frappe/frappe-bench/apps/frappe" ]; then
    echo "Bench already exists, skipping init"
    cd frappe-bench
    bench start
else
    echo "Creating new bench..."
fi

bench init --skip-redis-config-generation frappe-bench --version develop

cd frappe-bench


bench set-mariadb-host mariadb
bench set-redis-cache-host redis:6379
bench set-redis-queue-host redis:6379
bench set-redis-socketio-host redis:6379


sed -i '/redis/d' ./Procfile
sed -i '/watch/d' ./Procfile

bench get-app helpdesk --branch develop

bench new-site helpdesk.localhost \
--force \
--mariadb-root-password 123 \
--admin-password admin \
--no-mariadb-socket

bench --site helpdesk.localhost install-app helpdesk
bench --site helpdesk.localhost set-config developer_mode 1
bench --site helpdesk.localhost set-config mute_emails 1
bench --site helpdesk.localhost set-config server_script_enabled 1
bench --site helpdesk.localhost clear-cache
bench use helpdesk.localhost

bench start
```

### Version

Framework: v15.x.x-develop (fd783f0) (develop)
Helpdesk: v1.6.1 (develop)

### Installation method

docker

### Relevant log output / Stack trace / Full Error Message.

```shell

```
